#!/bin/sh
#from: https://samsclass.info/141/proj/pEth1.htm
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:ethereum/ethereum
sudo apt-get update
sudo apt-get install -y ethereum
cd
mkdir eth-test
cd eth-test
sudo curl https://raw.githubusercontent.com/BBOLDT86/Saphire/master/genesis.json
